### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nrkfeller**
changed "open in cloud shell" from cloning from installation branch to main branch

### CODE REVIEW

**Review by nrkfeller — COMMENTED** [review]
changed path to base folder rather than /installation-scripts

**Review by ghchinoy — COMMENTED** [review]
- can remove the branch, since it's main
- also repo should be only `https://github.com/GoogleCloudPlatform/genai-for-marketing`
- change `cloudshell_tutorial` param to `installation_scripts/tutorial.md`

**Review by nrkfeller — COMMENTED** [review]
updated with recommendations

**Review by ghchinoy — APPROVED** [review]
LGTM

**Comment by nrkfeller** [comment]
changed "open in cloud shell" from cloning from installation branch to main branch

**Pull request merged**
