### PR TITLE
Documentation changes from deploying E2E

### PR DESCRIPTION
**Pull request by awaemmanuel**
Documentation updates and recommendations.

### CODE REVIEW

**Comment by michaelwsherman** [comment]
We may have had a pretty big miscommunication here, my apologies. Did you connect to Agustin about working from the dev branch? Use those instructions, and then make your merge into dev, not main. LMK if you have questions.

**Comment by awaemmanuel** [comment]
> We may have had a pretty big miscommunication here, my apologies. Did you connect to Agustin about working from the dev branch? Use those instructions, and then make your merge into dev, not main. LMK if you have questions.
No I didn't know I had to work off dev. I'll try the instructions from there and let you know.

**Review by ghchinoy — APPROVED** [review]

**Review by michaelwsherman — APPROVED** [review]
LGTM. Note that github messed up the diff a bit and the old manual installation steps in their entirety are now  in manual-setup.md.

**Comment by awaemmanuel** [comment]
@michaelwsherman, abandoning this PR and sending a new one now.

**Pull request closed without merging**
